BacheloretteClient/Models/Bachelorette.cs
using System.Collections.Generic;
using System;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace BacheloretteClient.Models
{
    public class Bachelorette
    {
        public int BacheloretteId { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public string Job { get; set; }
        public string Hometown { get; set; }
        public int Season { get; set; }

        public static List<Bachelorette> GetAll()
        {
            var getAllResult = ApiHelper.GetAllBachelorette();
            var result = getAllResult.Result;

            JArray jsonResponse = JsonConvert.DeserializeObject<JArray>(result);
            List<Bachelorette> bachelorettesList =JsonConvert.DeserializeObject<List<Bachelorette>>(jsonResponse.ToString());
            return bachelorettesList;  
        }
        public static Bachelorette GetDetails(int id)
        {
          var apiCallTask = ApiHelper.GetBachelorette(id);
          var result = apiCallTask.Result;

          JObject jsonResponse = JsonConvert.DeserializeObject<JObject>(result);
          Bachelorette thisBachelorette = JsonConvert.DeserializeObject<Bachelorette>(jsonResponse.ToString());
          return thisBachelorette;
        }
        public static void Post(Bachelorette bachelorette)
        {
          string jsonBach = JsonConvert.SerializeObject(bachelorette);
          var apiCallTask = ApiHelper.PostBachelorette(jsonBach);
        }
        public static void Put(Bachelorette bachelorette)
        {
          string jsonBach = JsonConvert.SerializeObject(bachelorette);
          var apiCallTask = ApiHelper.PutBachelorette(bachelorette.BacheloretteId, jsonBach);
        }
        public static void Delete(int id)
        {
          var apiCallTask = ApiHelper.DeleteBachelorette(id);
        }
    }
}

BacheloretteClient/Controllers/BachelorettesController.cs
using BacheloretteClient.Models;
using Microsoft.AspNetCore.Mvc;

namespace BacheloretteClient.Controllers
{
  public class BachelorettesController : Controller
  {
    public IActionResult Index()
    {
      var allBachelorettes = Bachelorette.GetAll();
      return View(allBachelorettes);
    }
    [HttpPost]
    public IActionResult Index(Bachelorette bachelorette)
    {
      Bachelorette.Post(bachelorette);
      return RedirectToAction("Index");
    }
    public IActionResult Details(int id)
    {
      var bachelorette = Bachelorette.GetDetails(id);
      return View(bachelorette);
    }
    public IActionResult Edit(int id)
    {
      var bachelorette = Bachelorette.GetDetails(id);
      return View(bachelorette);
    }
    [HttpPost]
    public IActionResult Details(int id, Bachelorette bachelorette)
    {
      bachelorette.BacheloretteId = id;
      Bachelorette.Put(bachelorette);
      return RedirectToAction("Details", id);
    }
    public IActionResult Delete(int id)
    {
      Bachelorette.Delete(id);
      return RedirectToAction("Index");
    }
    public IActionResult Create()
    {
      return View();
    }
    [HttpPost]
    public IActionResult Create(Bachelorette newBachelorette)
    {
      Bachelorette.Post(newBachelorette);
      return RedirectToAction("Index");
    }
  }
}

BacheloretteClient/Controllers/ContestantController.cs
using BacheloretteClient.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System;

using Microsoft.AspNetCore.Mvc.Rendering;

namespace BacheloretteClient.Controllers
{
    [Route("/bachelorettes/{bacheloretteId}/[controller]")]
    public class ContestantsController : Controller
    {
        //   [HttpGet("/bachelorettes/{bacheloretteId}/contestants/")]
        public IActionResult Index(int BacheloretteId)
        {
            Console.WriteLine("Line-15 Bachelor ID is " + BacheloretteId);
            var allContestants = Contestant.GetAll(BacheloretteId); //GetAll is NOT filtering Contestant records by Bachelor ID. 
            return View(allContestants);
        }

        [HttpGet("/bachelorettes/{bacheloretteId}/contestants/details/{id}")]
        public IActionResult Details(int id, int bacheloretteId)
        {
            Console.WriteLine("Line-22 Bachelor ID is ");
            var thisContestant = Contestant.GetDetails(id, bacheloretteId);
            return View(thisContestant);
        }

        [HttpGet("/bachelorettes/contestants/create")]
        public IActionResult Create()
        {
            Console.WriteLine("Line-30 Bachelor ID is ");
            List<Bachelorette> bachelorettesList = Bachelorette.GetAll();
            ViewBag.BacheloretteId = new SelectList(bachelorettesList, "BacheloretteId", "Name");
            return View();
        }

        [HttpPost("/bachelorettes/contestants/create")]  //gets routed to https://localhost:5006/bachelorettes/contestants/create   
        public IActionResult Create(Contestant newContestant, int bacheloretteId)
        {
            Console.WriteLine("Bachelor ID is !!!!! line 41 " + newContestant.BacheloretteId);
            newContestant.BacheloretteId = bacheloretteId;
            Contestant.Post(newContestant);
            Console.WriteLine("Bachelor ID is !!!!! line 49");
            return RedirectToAction("Index", new { BacheloretteId = bacheloretteId });
        }

    }
}

BacheloretteClient/Views/Bachelorettes/Create.cshtml
<h1>Create New Bachelorette</h1>

@model BacheloretteClient.Models.Bachelorette

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  @Html.LabelFor(model => model.Age)
  @Html.TextBoxFor(model => model.Age)

  @Html.LabelFor(model => model.Job)
  @Html.TextBoxFor(model => model.Job)

  @Html.LabelFor(model => model.Hometown)
  @Html.TextBoxFor(model => model.Hometown)

  @Html.LabelFor(model => model.Season)
  @Html.TextBoxFor(model => model.Season)

  <input type="submit" value="Submit" class="btn btn-default" required="true" />
}

<p>@Html.ActionLink("Return", "Index");</p>

BacheloretteClient/Views/Bachelorettes/Details.cshtml
@{
      ViewData["Title"] = "Details";
}

<ul>
    <li>ID: @Model.BacheloretteId</li>
    <li>Name: @Model.Name</li>
    <li>Age: @Model.Age</li>
    <li>Job: @Model
    <li>Hometown: @Model.Hometown</li>
    <li>Season: @Model.Season</li>
</ul>

<p>@Html.ActionLink("See the contestants vying for her heart", "Index", "Contestants",  new {bacheloretteId = Model.BacheloretteId})</p>

<p>@Html.ActionLink("Edit","Edit", new { id = Model.BacheloretteId})</p>
<p>@Html.ActionLink("Delete","Delete", new { id = Model.BacheloretteId})</p>
<p>@Html.ActionLink("Return","Index")</p>

BacheloretteClient/Views/Bachelorettes/Edit.cshtml
<h1>Edit Bachelorette Details</h1>

@model BacheloretteClient.Models.Bachelorette

@using (Html.BeginForm("Details","Bachelorettes", new {id = Model.BacheloretteId} ))
{
  @Html.HiddenFor(model => model.BacheloretteId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  @Html.LabelFor(model => model.Age)
  @Html.EditorFor(model => model.Age)

  @Html.LabelFor(model => model.Job)
  @Html.EditorFor(model => model.Job)

  @Html.LabelFor(model => model.Hometown)
  @Html.EditorFor(model => model.Hometown)

  @Html.LabelFor(model => model.Season)
  @Html.EditorFor(model => model.Season)

  <input type="submit" value="Save" class="btn btn-default" required="true" />
}

<p>@Html.ActionLink("Return to details", "Details", new {id = Model.BacheloretteId})</p>

BacheloretteClient/Views/Bachelorettes/Index.cshtml
<h1>All Bachelorettes:</h1>

<ol>
@foreach (Bachelorette bachelorette in Model)
{
    <ul>
        <li>ID: @bachelorette.BacheloretteId</li>
        <li>Name: @bachelorette.Name</li>
        <li>Age: @bachelorette.Age</li>
        <li>Job: @bachelorette.Job</li>
        <li>Hometown: @bachelorette.Hometown</li>
        <li>Season: @bachelorette.Season</li>
    </ul>
    <a href="/Bachelorettes/Details/@(bachelorette.BacheloretteId)"><p>View Details</p></a>
    <br>
}
</ol>

<p>@Html.ActionLink("Add a bachelorette","Create")</p>